---
ec2Private1SubnetAclEntryOut500:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate1Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private1SubnetNetworkAcl
    RuleNumber: '500'
    Protocol: "-1"
    RuleAction: allow
    Egress: 'true'
    CidrBlock: 10.248.0.0/16
