---
ec2Public1SubnetNetworkAcl:
  Type: AWS::EC2::NetworkAcl
  Properties:
    VpcId:
      Ref: ec2VPC
    Tags:
    - Key: Stack
      Value:
        Ref: AWS::StackName
    - Key: Owner
      Value:
        Ref: kOwnerService
    - Key: Env
      Value:
        Ref: lStackEnv
    - Key: Name
      Value:
        Fn::Join:
        - "-"
        - - Ref: kOwnerService
          - Ref: lStackEnv
          - public1-nacl
          - Fn::FindInMap:
            - RegionMap
            - Ref: AWS::Region
            - AbbrRegion
