---
ec2Public1SubnetAclEntryOut100:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
    NetworkAclId:
      Ref: ec2Public1SubnetNetworkAcl
    RuleNumber: '100'
    Protocol: "-1"
    RuleAction: allow
    Egress: 'true'
    CidrBlock: 0.0.0.0/0
