---
ec2Private1SubnetAclEntryOut100:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate1Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private1SubnetNetworkAcl
    RuleNumber: '100'
    Protocol: "-1"
    RuleAction: allow
    Egress: 'true'
    CidrBlock:
      Ref: aVPCCIDRBlock
