---
ec2Pri2DefaultRoute:
  Type: AWS::EC2::Route
  Condition: AnyPrivate2Subnet
  Properties:
    RouteTableId:
      Ref: ec2Private2RouteTable
    DestinationCidrBlock: 0.0.0.0/0
    GatewayId:
      Ref: ec2InternetGW
