---
ec2Private2SubnetRouteTableAssocAZ1:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Condition: Private2AZ1
  Properties:
    SubnetId:
      Ref: ec2Private2SubnetAZ1
    RouteTableId:
      Ref: ec2Private2RouteTable
