---
ec2Private2SubnetAclEntryOut300:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate2Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private2SubnetNetworkAcl
    RuleNumber: '300'
    Protocol: '6'
    PortRange:
      From: '80'
      To: '80'
    RuleAction: allow
    Egress: 'true'
    CidrBlock: 0.0.0.0/0
