---
ec2Private2SubnetAclEntryIn500:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate2Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private2SubnetNetworkAcl
    RuleNumber: '500'
    Protocol: "-1"
    RuleAction: allow
    Egress: 'false'
    CidrBlock: 10.248.0.0/16
