---
ec2Private2SubnetNetworkAclAssocAZ2:
  Type: AWS::EC2::SubnetNetworkAclAssociation
  Condition: Private2AZ2
  Properties:
    SubnetId:
      Ref: ec2Private2SubnetAZ2
    NetworkAclId:
      Ref: ec2Private2SubnetNetworkAcl
