---
ec2Private1SubnetNetworkAclAssocAZ3:
  Type: AWS::EC2::SubnetNetworkAclAssociation
  Condition: Private1AZ3
  Properties:
    SubnetId:
      Ref: ec2Private1SubnetAZ3
    NetworkAclId:
      Ref: ec2Private1SubnetNetworkAcl
