---
ec2Private2SubnetAclEntryOut400:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate2Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private2SubnetNetworkAcl
    RuleNumber: '400'
    Protocol: '17'
    PortRange:
      From: '123'
      To: '123'
    RuleAction: allow
    Egress: 'true'
    CidrBlock: 0.0.0.0/0
