---
ec2Private1SubnetAclEntryIn300:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate1Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private1SubnetNetworkAcl
    RuleNumber: '300'
    Protocol: '17'
    PortRange:
      From: '1024'
      To: '65535'
    RuleAction: allow
    Egress: 'false'
    CidrBlock: 0.0.0.0/0
