---
ec2Private1SubnetAclEntryIn200:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate1Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private1SubnetNetworkAcl
    RuleNumber: '200'
    Protocol: '6'
    PortRange:
      From: '1024'
      To: '65535'
    RuleAction: allow
    Egress: 'false'
    CidrBlock: 0.0.0.0/0
