---
ec2Private2SubnetAclEntryIn100:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate2Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private2SubnetNetworkAcl
    RuleNumber: '100'
    Protocol: "-1"
    RuleAction: allow
    Egress: 'false'
    CidrBlock:
      Ref: aVPCCIDRBlock
