---
ec2Private2SubnetAclEntryOut200:
  Type: AWS::EC2::NetworkAclEntry
  Condition: AnyPrivate2Subnet
  Properties:
    NetworkAclId:
      Ref: ec2Private2SubnetNetworkAcl
    RuleNumber: '200'
    Protocol: '6'
    PortRange:
      From: '443'
      To: '443'
    RuleAction: allow
    Egress: 'true'
    CidrBlock: 0.0.0.0/0
