---
ec2Public1SubnetRouteTableAssocAZ3:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Condition: Public1AZ3
  Properties:
    SubnetId:
      Ref: ec2Public1SubnetAZ3
    RouteTableId:
      Ref: ec2Public1RouteTable
