---
ec2Public1SubnetNetworkAclAssocAZ2:
  Type: AWS::EC2::SubnetNetworkAclAssociation
  Condition: Public1AZ2
  Properties:
    SubnetId:
      Ref: ec2Public1SubnetAZ2
    NetworkAclId:
      Ref: ec2Public1SubnetNetworkAcl
